config/routes.rb
Rails.application.routes.draw do
  get '/artists', to: 'artists#index'
  get '/artists/:id', to:'artists#show', as: 'artist'
  get 'artists/index'

  get 'artists/show'

   root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
#app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        if !params[:artist_name].empty?
            @artists = RSpotify::Artist.search(params[:artist_name])
        else
            redirect_to root_path
        end
    end
    def show
       @artist = RSpotify::Artist.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
    def renderArtistImage(images)
        return 'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-disc-256.png' unless images
        firstImage = images[1]
        return 'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-disc-256.png' unless firstImage
        url = firstImage['url']
        return url if url
        "https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-disc-256.png"
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/index.html.erb
<nav class="nav-spotify">
    <div class="header-spotify">
        <a href="/">
            <img alt="Spotify" class="logo-spotify" src="http://www.clker.com/cliparts/5/c/a/f/141490005811489798026274.spotify-logo-horizontal-white-rgb-hi.png">
        </a>
        <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
            <div class="form form-artist">
            <%= text_field_tag(:artist_name, "", value: params[:artist_name]) %>
            </div>
        <% end %>
    </div>
    <div class="menu-spotify">
        <span>By Emerson Laurentino and Victor Meneghini</span>
    </div>
</nav>
<div class="content-spotify">
    <% @artists.each do |artist| %>
        <a href="<%= artist_path(artist.id) %>" class="capa-spotify">
            <img src="<%= renderArtistImage artist.images %>">
            <span><%= artist.name %></span>
        </a>
    <% end %>
</div>

app/views/artists/show.html.erb
<nav class="nav-spotify">
    <div class="header-spotify">
        <a href="/">
            <img alt="Spotify" class="logo-spotify" src="http://www.clker.com/cliparts/5/c/a/f/141490005811489798026274.spotify-logo-horizontal-white-rgb-hi.png">
        </a>
        <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
            <div class="form form-artist">
            <%= text_field_tag(:artist_name, "", value: @artist.name) %>
            </div>
        <% end %>
    </div>
    <div class="menu-spotify">
        <span>By Emerson Laurentino and Victor Meneghini</span>
    </div>
</nav>
<div class="content-show-spotify">
    <% @artist.albums(country: 'US').each do |album| %>
        <a href="spotify:album:<%= album.id %>" class="capa-spotify">
            <img src="<%= renderArtistImage album.images %>">
            <span><%= album.name %></span>
            <ul>
                <% album.tracks.each do |track| %>
                    <li>
                        <%= track.name %>
                    </li>
                <% end %>
            </ul>
        </a>
    <% end %>
</div>
 

app/views/home/index.html.erb
<div class="home">
    <div class="home-logo">
        <a href="/">
            <img alt="Spotify" class="logo-spotify" src="http://www.clker.com/cliparts/5/c/a/f/141490005811489798026274.spotify-logo-horizontal-white-rgb-hi.png">
        </a>
    </div>
    <%= form_tag artists_path, method: "get", class: "form-home" do %>
        <div class="form">
            <%= text_field_tag(:artist_name, "", placeholder: "Procurar um artistas?") %>
            <%= submit_tag "Procurar", class: "btn" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>